### ISSUE TITLE
Add support for SameSite=None; Secure

### ISSUE THREAD

**Issue by 9mido** [zvyn/django-samesite-none#1]
https://web.dev/samesite-cookie-recipes/

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

https://digiday.com/media/what-is-chrome-samesite/

**Comment by zvyn** [comment]
This middleware does not affect your ability to set `Secure` on cookies at all. It simply fixes a bug where setting `SameSite` to `"None"` was impossible for some pre-defined (session, csrf) cookies.

https://docs.djangoproject.com/en/2.2/ref/settings/#csrf-cookie-secure
https://docs.djangoproject.com/en/2.2/ref/settings/#session-cookie-secure
